version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpressdbase.chv6tickgx5d.us-east-1.rds.amazonaws.com
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=wordpressdbase
      - WORDPRESS_DB_NAME=wordpressdbase